### ISSUE TITLE
Standardize domain component helper

### ISSUE THREAD

**Issue by mjclemente** [mjclemente/sendgrid.cfc#11]
The domain helper cfc is used in `createAuthenticatedDomain()`, but unlike the other helpers, it's manually constructed within the function, instead of being passed in.

It would be best if this operated in the same manner as the other components that utilize helpers.

**Comment by mjclemente** [comment]
@tbenton Question about `createAuthenticatedDomain()` - instead of accepting the domain helper CFC, it accepts all the parameters and builds the helper component within the function. This seems to defeat the purpose of the helper.

I was thinking of refactoring this to function like `updateEventWebhookSettings()` and `createCampaign()` do, accepting the helper object, fully built, instead of all the parameters, which can be a bit messy.

Thoughts on this change? Would this break your use? Is there are reason this one is set up differently than the others? Would it be better for me to add a new method to use the helper and leave this one able to accept all params?

**Comment by tbenton** [comment]
@mjclemente I don't have any issues with the changes you are proposing.  It will require me to to change the code but it should not be a huge issue.

I don't recall the decision point other than the build function needed deal with the IP array correctly.  If I recall I had some issues with this API call.   

Please let me know if you need any testing on my part.

**Comment by mjclemente** [comment]
@tbenton This one did get updated/changed with the release. In 1.0.0, `createAuthenticatedDomain()` takes either a struct or the helper component, which I believe that this will be breaking for you. Just a heads up. And if problems arise due to this, let me know. 

Cheers!
