### ISSUE TITLE
Add support for email address validation API

### ISSUE THREAD

**Issue by davidsf** [mjclemente/sendgrid.cfc#2]
Sendgrid has an API for email validation of an email addres. 

https://sendgrid.com/docs/ui/managing-contacts/email-address-validation/

It should be great that sendgrid.cfc support it.

Thanks!

**Comment by mjclemente** [comment]
Absolutely. Makes a ton of sense. I see that you even put in a PR for it. Thank you!! 🙏

I'll take a look and get that merged as soon as I have a minute. Really appreciate it.

**Comment by mjclemente** [comment]
I merged your pull request on develop, but I'm going to need to do a little more digging into the documentation for this. 

It appears that the SendGrid email validation API may require a separate API key from their primary API. If that's the case, I'll have to determine the best way to incorporate that functionality. Needing a separate key is bound to be a source of confusion/frustration. Additionally, it doesn't look like they've added the validation endpoint to their officially supported clients.

**Comment by mjclemente** [comment]
So, sure enough, the email validation endpoint required a different API key than the rest of SendGrid's API (https://sendgrid.com/docs/ui/managing-contacts/email-address-validation/). 

> You are required to create a brand new API key that will only be used for Email Address Validation.

I'm not sure the best way to handle this and would appreciate any feedback you have.

My current line of thinking is just to proceed with adding the endpoint and then beefing up the documentation to make it clear that if you're using the component to validate emails it requires a different API key than if you're using it to send emails. 

Alternatively, I suppose the wrapper could be updated to accept two different API keys on init, one for sending, one for validating. But that seems like it would unnecessarily complicate things.

Finally, I could just throw together a smaller SendGrid API wrapper just for using the validation endpoint and point people to that in the documentation.

Thoughts?

**Comment by davidsf** [comment]
I will go to the two API keys in init, with a clear in a comment about the second api key for the email validation. I think is easy to implement and use for the users. If the user not use the email validation, he doesn't need to configure that api key. 

I will try to do it with another PR so you can review it.

**Comment by mjclemente** [comment]
Thanks for the response! But please don't make that new PR just yet. I wasn't looking for you to do any more work - just your perspective on the design problem, to help me understand other point of view of the issue. I'm not entirely sold on the two API key solution. I should have this issue closed by the end of the week, one way or the other. Thanks for your patience, raising the issue, and the initial PR!

**Comment by mjclemente** [comment]
While I'm still not sure what the most "proper" approach would be, we'll take the route you suggested, as you made the initial feature request and added the PR for it.

I'll work on adding support for the second API key for email validation. Hoping to have it released by the end of the week. (Also hoping SendGrid eventually switches to supporting email validation via their primary API key). 

Cheers!

**Comment by mjclemente** [comment]
Ok, should be all good now. Thanks for the PR and raising this issue!
